# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [1]:
# your code goes here
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [2]:
filtered_data = df[(df["Total Claim Amount"] < 1000) &  (df["Response"] == "Yes")]
filtered_data

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [5]:
df["monthly_premium_auto"]

0         61
1         64
2        100
3         97
4        117
        ...
10905    253
10906     65
10907    201
10908    158
10909    101
Name: monthly_premium_auto, Length: 10910, dtype: int64

In [4]:
#Clean the columns with Lower case and Replace " " with "_"
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [6]:
yes_response = df[df["response"] == "Yes"]
yes_response.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [7]:
summary = yes_response.groupby(["gender", "policy_type"])[["monthly_premium_auto","customer_lifetime_value", "total_claim_amount"]].mean().round(2).reset_index()
summary.head()

,gender,policy_type,monthly_premium_auto,customer_lifetime_value,total_claim_amount
0,F,Corporate Auto,94.30,7712.63,433.74
1,F,Personal Auto,99.00,8339.79,452.97
2,F,Special Auto,92.31,7691.58,453.28
3,M,Corporate Auto,92.19,7944.47,408.58
4,M,Personal Auto,91.09,7448.38,457.01

In [8]:
summary["profit_score"] = summary["customer_lifetime_value"] - summary["total_claim_amount"]
summary.head()

,gender,policy_type,monthly_premium_auto,customer_lifetime_value,total_claim_amount,profit_score
0,F,Corporate Auto,94.30,7712.63,433.74,7278.89
1,F,Personal Auto,99.00,8339.79,452.97,7886.82
2,F,Special Auto,92.31,7691.58,453.28,7238.30
3,M,Corporate Auto,92.19,7944.47,408.58,7535.89
4,M,Personal Auto,91.09,7448.38,457.01,6991.37

In [9]:
#Check profitablity
summary_sorted = summary.sort_values(by="profit_score", ascending= False).reset_index(drop=True)
print(summary_sorted)

  gender     policy_type  monthly_premium_auto  customer_lifetime_value  \
0      F   Personal Auto                 99.00                  8339.79
1      M    Special Auto                 86.34                  8247.09
2      M  Corporate Auto                 92.19                  7944.47
3      F  Corporate Auto                 94.30                  7712.63
4      F    Special Auto                 92.31                  7691.58
5      M   Personal Auto                 91.09                  7448.38

   total_claim_amount  profit_score
0              452.97       7886.82
1              429.53       7817.56
2              408.58       7535.89
3              433.74       7278.89
4              453.28       7238.30
5              457.01       6991.37

In [10]:
#Low risk Segments
low_risk = summary.sort_values(by="total_claim_amount").reset_index(drop=True)
low_risk

,gender,policy_type,monthly_premium_auto,customer_lifetime_value,total_claim_amount,profit_score
0,M,Corporate Auto,92.19,7944.47,408.58,7535.89
1,M,Special Auto,86.34,8247.09,429.53,7817.56
2,F,Corporate Auto,94.30,7712.63,433.74,7278.89
3,F,Personal Auto,99.00,8339.79,452.97,7886.82
4,F,Special Auto,92.31,7691.58,453.28,7238.30
5,M,Personal Auto,91.09,7448.38,457.01,6991.37

In [15]:
df["effective_to_date"].unique()

array(['2/18/11', '1/18/11', '2/10/11', '1/11/11', '1/17/11', '2/14/11',
       '2/24/11', '1/19/11', '1/4/11', '1/2/11', '2/7/11', '1/31/11',
       '1/26/11', '2/28/11', '1/16/11', '2/26/11', '2/23/11', '1/15/11',
       '2/2/11', '2/15/11', '1/24/11', '2/21/11', '2/22/11', '1/7/11',
       '1/28/11', '2/8/11', '2/12/11', '2/20/11', '1/5/11', '2/19/11',
       '1/3/11', '2/3/11', '1/22/11', '1/23/11', '2/5/11', '2/13/11',
       '1/25/11', '2/16/11', '2/1/11', '1/27/11', '1/12/11', '1/20/11',
       '2/6/11', '2/11/11', '1/21/11', '1/29/11', '1/9/11', '2/9/11',
       '2/27/11', '1/1/11', '2/17/11', '2/25/11', '1/13/11', '1/6/11',
       '2/4/11', '1/14/11', '1/10/11', '1/8/11', '1/30/11'], dtype=object)

In [16]:
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])

C:\Users\pol\AppData\Local\Temp\ipykernel_69448\1646485608.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])

In [17]:
df["month"] = df["effective_to_date"].dt.month_name()

In [22]:
#Convert to Date
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"])

#Extract month
df["month"] = df["effective_to_date"].dt.month_name()

#Create Table
table = pd.pivot_table(
    df,
    index="state",
    columns="month",
    aggfunc="size",
    fill_value=0
)

print(table)

month       February  January
state
Arizona          929     1008
California      1634     1918
Nevada           442      551
Oregon          1344     1565
Washington       425      463

In [25]:
pd.pivot_table(
    df.assign(month=pd.to_datetime(df["effective_to_date"]).dt.month_name()),
    index="gender",
    columns="month",
    aggfunc="size",
    fill_value=0
)

month   February  January
gender
F           2649     2924
M           2443     2894

In [21]:
policies_by_state_mmonth

month       January  February
state
Arizona        1008       929
California     1918      1634
Nevada          551       442
Oregon         1565      1344
Washington      463       425

In [27]:
#Question 4

state_counts = df["state"].value_counts
state_counts

<bound method IndexOpsMixin.value_counts of 0           Arizona
1        California
2        Washington
3            Oregon
4            Oregon
            ...
10905        Nevada
10906        Oregon
10907       Arizona
10908    California
10909           NaN
Name: state, Length: 10910, dtype: object>

In [36]:
state_count = df.groupby("state").size()
filtered_state = state_count[state_count > 1000]
filtered_state

state
Arizona       1937
California    3552
Oregon        2909
dtype: int64

In [37]:
df["state"].value_counts()[lambda x: x > 900]

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Name: count, dtype: int64

In [44]:
# your code goes here
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [45]:
#Clean the columns with Lower case and Replace " " with "_"
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [46]:
Life_time = df.groupby(["education", "gender"]).agg(
    max_customer_value=("customer_lifetime_value", "max"),
    min_customer_value=("customer_lifetime_value", "min"),
    median_customer_value=("customer_lifetime_value", "median")
).round(2).reset_index()

Life_time.head()

,education,gender,max_customer_value,min_customer_value,median_customer_value
0,Bachelor,F,73225.96,1904.00,5640.51
1,Bachelor,M,67907.27,1898.01,5548.03
2,College,F,61850.19,1898.68,5623.61
3,College,M,61134.68,1918.12,6005.85
4,Doctor,F,44856.11,2395.57,5332.46

In [50]:
Life_time.sort_values(by="median_customer_value", ascending=False)

,education,gender,max_customer_value,min_customer_value,median_customer_value
7,High School or Below,M,83325.38,1940.98,6286.73
6,High School or Below,F,55277.45,2144.92,6039.55
3,College,M,61134.68,1918.12,6005.85
8,Master,F,51016.07,2417.78,5729.86
0,Bachelor,F,73225.96,1904.00,5640.51
2,College,F,61850.19,1898.68,5623.61
9,Master,M,50568.26,2272.31,5579.10
5,Doctor,M,32677.34,2267.60,5577.67
1,Bachelor,M,67907.27,1898.01,5548.03
4,Doctor,F,44856.11,2395.57,5332.46